name: checking

on: push 
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
        - name: running file
          run: node index.js
  second-job:
    runs-on: ubuntu-latest
    setps: 
        - name: testing
          needs: first-job
          run: node -v